import Link from "next/link";
import { Compass, Crown, Sparkles, Star, WandSparkles } from "lucide-react";
import { getStarTrailProgress, getStarTrailTheme } from "@/lib/achievements/themes";

type Props = { childId?: string; themeKey: string; stars: number; preview?: boolean };

const looks = {
  magic_kingdom: { shell: "from-violet-700 via-fuchsia-600 to-amber-400 shadow-violet-200/70", label: "text-violet-100", token: "from-amber-200 via-amber-400 to-orange-500", dark: "bg-violet-950/30", icon: Crown },
  hogwarts_adventure: { shell: "from-slate-950 via-indigo-950 to-violet-800 shadow-indigo-200/70", label: "text-amber-100", token: "from-yellow-200 via-amber-400 to-yellow-700", dark: "bg-slate-950/55", icon: WandSparkles },
  middle_earth: { shell: "from-emerald-950 via-teal-900 to-amber-800 shadow-emerald-200/70", label: "text-amber-100", token: "from-yellow-200 via-amber-400 to-orange-700", dark: "bg-emerald-950/60", icon: Compass },
} as const;

function Scene({ themeKey }: { themeKey: string }) {
  if (themeKey === "hogwarts_adventure") return <svg aria-hidden="true" className="pointer-events-none absolute inset-0 h-full w-full opacity-50" preserveAspectRatio="xMidYMid slice" viewBox="0 0 800 380"><defs><radialGradient id="wizard-glow"><stop stopColor="#fde68a" stopOpacity=".34"/><stop offset="1" stopColor="#fde68a" stopOpacity="0"/></radialGradient></defs><circle cx="640" cy="70" r="130" fill="url(#wizard-glow)"/><path d="M0 350V260l70-25 25-70 26 70 40 12V180l45-15 15-100 18 100 49 15v55l80-20 30-80 35 80 60 12V150l34-12 18-75 17 75 38 12v105l70-25 33-70 35 70 70 22v98Z" fill="#11102b" opacity=".8"/><path d="M0 350q200-70 400 0t400-15v45H0Z" fill="#0b1025"/><g fill="#fbbf24"><circle cx="92" cy="54" r="2"/><circle cx="270" cy="84" r="2"/><circle cx="496" cy="42" r="3"/><circle cx="720" cy="92" r="2"/><path d="m385 45 4 11 11 4-11 4-4 11-4-11-11-4 11-4Z"/></g></svg>;
  if (themeKey === "middle_earth") return <svg aria-hidden="true" className="pointer-events-none absolute inset-0 h-full w-full opacity-55" preserveAspectRatio="xMidYMid slice" viewBox="0 0 800 380"><defs><radialGradient id="earth-glow"><stop stopColor="#fcd34d" stopOpacity=".42"/><stop offset="1" stopColor="#fcd34d" stopOpacity="0"/></radialGradient></defs><circle cx="630" cy="70" r="145" fill="url(#earth-glow)"/><path d="M0 300 110 160l50 55 75-115 90 150 80-120 130 150 90-135 175 170v65H0Z" fill="#064e3b"/><path d="m0 340 145-120 120 95 100-80 120 100 120-90 195 100v35H0Z" fill="#022c22"/><path d="M0 355q220-20 350-5t450-25v55H0Z" fill="#052e2b"/><path d="M550 380q-40-40-10-70t-20-65" fill="none" stroke="#eab308" strokeOpacity=".5" strokeWidth="6" strokeLinecap="round"/></svg>;
  return <><span aria-hidden="true" className="absolute -right-12 -top-12 size-40 rounded-full bg-amber-200/30 blur-2xl"/><span aria-hidden="true" className="absolute -bottom-16 left-1/3 size-36 rounded-full bg-sky-300/20 blur-2xl"/><span aria-hidden="true" className="absolute right-14 top-20 rotate-12 text-5xl text-white/15">✦</span></>;
}

export function StarTrailCard({ childId, themeKey, stars, preview = false }: Props) {
  const theme = getStarTrailTheme(themeKey);
  const look = looks[theme.key];
  const progress = getStarTrailProgress(theme.key, stars);
  const Icon = look.icon;
  return <section aria-label={`${theme.name} Star Trail${preview ? " preview" : ""}`} className={`relative overflow-hidden rounded-3xl border border-white/20 bg-gradient-to-br ${look.shell} text-white shadow-xl`}>
    <Scene themeKey={theme.key}/>
    <div className={`relative ${preview ? "p-4" : "p-4 sm:p-5"}`}>
      <div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className={`flex items-center gap-1.5 text-xs font-bold uppercase tracking-[.15em] ${look.label}`}><Icon aria-hidden="true" size={16}/>{theme.name}</p><h2 className="mt-1 text-xl font-black tracking-tight sm:text-2xl">{progress.title}</h2><p className="mt-1 text-sm font-semibold text-white/90">{theme.intro}</p></div>{!preview && childId ? <Link className="shrink-0 rounded-xl border border-white/30 bg-white/15 px-3 py-2 text-xs font-extrabold text-white shadow-sm backdrop-blur transition hover:bg-white/25 sm:text-sm" href={`/achievements?child=${childId}`}>Achievements</Link> : null}</div>
      <div className="mt-4 flex items-center gap-4 rounded-3xl border border-white/25 bg-white/15 p-3 shadow-inner backdrop-blur-sm"><div aria-label={`${stars} stars`} className={`relative grid size-20 shrink-0 place-items-center rounded-full border-4 border-amber-100 bg-gradient-to-br ${look.token} text-center text-white shadow-lg shadow-black/30`}><Star aria-hidden="true" className="absolute -top-2 -right-2 fill-yellow-100 text-yellow-100" size={21}/><span><strong className="block text-3xl leading-none">{stars}</strong><small className="mt-1 block text-[10px] font-black uppercase tracking-wider">stars</small></span></div><div><p className={`text-xs font-bold uppercase tracking-[.14em] ${look.label}`}>{theme.pouch}</p><p className="mt-1 text-base font-extrabold">{progress.nextStars ? `${progress.nextStars - stars} more stars to go!` : "Every weekly badge is yours!"}</p><p className="mt-1 text-xs font-semibold text-white/85">{progress.nextStars ? theme.encouragement : theme.complete}</p></div></div>
      <div className="mt-5"><div className="flex items-center justify-between gap-2"><p className={`flex items-center gap-1 text-xs font-black uppercase tracking-[.15em] ${look.label}`}><Sparkles aria-hidden="true" size={13}/>{theme.path}</p><p className="text-right text-xs font-bold text-white/90">{progress.nextStars ? `Next: ${theme.milestones.find((milestone) => milestone.stars === progress.nextStars)?.name}` : "Trail complete!"}</p></div><ol className="relative mt-3 grid grid-cols-5 gap-1 before:absolute before:left-[10%] before:right-[10%] before:top-5 before:h-1 before:rounded-full before:bg-white/30">{[{ stars: 1, name: theme.starter }, ...theme.milestones].map((milestone) => <li className="relative min-w-0 text-center" key={milestone.stars}><span className={`mx-auto grid size-10 place-items-center rounded-full border-2 text-xl shadow-lg ${stars >= milestone.stars ? `border-amber-100 bg-gradient-to-br ${look.token} text-white` : `border-white/35 ${look.dark} text-white/65`}`}><Star aria-hidden="true" className={stars >= milestone.stars ? "fill-current" : ""} size={19}/></span><small className="mt-1 block text-[9px] font-extrabold leading-tight text-white/95 sm:text-[10px]">{milestone.name}</small></li>)}</ol></div>
    </div>
  </section>;
}
